version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.0.0
    ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
    - ZOOKEEPER_SERVER_ID=1
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
    - ZOOKEEPER_INIT_LIMIT=5
    - ZOOKEEPER_SYNC_LIMIT=2
    - ZOOKEEPER_SERVERS=zookeeper:2888:3888
  kafka:
    image: confluentinc/cp-kafka:3.0.0
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BROKER_ID=1
  producer:
    image: confluentinc/cp-kafka
    depends_on:
    - zookeeper
    - kafka
    environment:
    - COMPONENT=kafka-producer-perf-test
    command:
    - sh
    - -c
    - |
      set -x
      sleep 10
      kafka-topics --zookeeper zookeeper:2181 \
      --create --if-not-exists \
      --topic topic1 --replication-factor 1 --partition 1
      kafka-producer-perf-test \
      --topic topic1 \
      --num-records 10000 \
      --record-size 500 \
      --throughput 10 \
      --producer-props bootstrap.servers=kafka:9092
  consumer:
    image: everpeace/reactive-kafka-throttlable-consumer
    depends_on:
    - zookeeper
    - kafka
    - producer
    environment:
    - FAKE_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
    - FAKE_CONSUMER_TOPIC=topic1
    - FAKE_CONSUMER_THROTTLE=100
    - FAKE_CONSUMER_LOG_PER=10